aliases:
  - alias: '!bruh'
    command: '!playsound'
    arguments:
      - 'bruh'
  - alias: '!doit'
    command: '!playsound'
    arguments:
      - 'doit'
  - alias: '!silence'
    command: '!!mute'