applications:
-   constructor: Dice
    path: './Applications/Dice.js'
-   constructor: SoundPlayer
    path: './Applications/SoundPlayer.js'
    config:
      paths:
        mute_duration: 1000 * 60 * 2
        sounds: './resources/sounds/'
        config: './resources/config/sounds.yaml'