clients:
  - constructor: TwitchClient
    path: './Clients/Twitch.js'
    config:
      debug: false
      username:
      password:
      token:
  - constructor: CLIClient
    path: './Clients/CLI.js'
    config:
      color: 'yellow'