clients:
  - constructor: TwitchClient
    path: './Clients/Twitch.js'
    config:
      debug: true
      username:
      password:
      token:
  - constructor: CLIClient
    path: './Clients/CLI.js'